### ISSUE TITLE
 DevOpsProdigy KubeGraf Node's Dashboard is broken

### ISSUE THREAD

**Issue by dmitrievav** [devopsprodigy/kubegraf#11]
`kubelet_running_pod_count`, `container_cpu_usage_seconds_total` and `container_memory_usage_bytes` have no label `node`

Example:

`kubelet_running_pod_count{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_instance_type="m5a.large",beta_kubernetes_io_os="linux",failure_domain_beta_kubernetes_io_region="eu-central-1",failure_domain_beta_kubernetes_io_zone="eu-central-1a",instance="ip-10-102-36-19.eu-central-1.compute.internal",job="kubernetes-nodes",kops_k8s_io_instancegroup="nodes",kubernetes_io_hostname="ip-10-102-36-19.eu-central-1.compute.internal",kubernetes_io_role="node"}`

**Comment by SergeiSporyshev** [comment]
Hi! Thank you for your PR
I think this issue (https://github.com/devopsprodigy/kubegraf/issues/9) will help you

**Comment by dmitrievav** [comment]
Adding to my prometheus.yml following rules solved the issue

```
- job_name: 'kubernetes-nodes-cadvisor'
  ...
  relabel_configs:
    ...
    # add node label for DevOpsProdigy KubeGraf compatibility
    - action: labelmap
      regex: __meta_kubernetes_node_label_kubernetes_io_hostname
      replacement: node

- job_name: 'kubernetes-nodes'
  ...
  relabel_configs:
    ...
    # add node label for DevOpsProdigy KubeGraf compatibility
    - action: labelmap
      regex: __meta_kubernetes_node_label_kubernetes_io_hostname
      replacement: node
```

And here is Prometheus documentation: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
