### ISSUE TITLE
kubegraf on EKS

### ISSUE THREAD

**Issue by jicowan** [devopsprodigy/kubegraf#29]
The ca/bearer token works for EKS, however, I'm not sure what minimum permissions to assign to the service account that corresponds to the bearer token. the service account assigned to my grafana pod has the following permissions: 
```
rules:
  - verbs:
      - use
    apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames: 
      - grafana
```
